[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "@google/generative-ai", "@supabase/supabase-js", "@supabase/ssr"]
  included_files = ["public/**"]